// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewStudent struct {
	Name string `json:"name"`
	Nim  string `json:"nim"`
}

type Student struct {
	ID   string `json:"_id" bson:"_id"`
	Name string `json:"name"`
	Nim  string `json:"nim"`
}
